/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pr.gui;

import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;

import pr.logic.Pattern;
import pr.logic.PatternRecognizer;
/**
 *
 * @author João Hudson
 * @version 1.0
 */
public class MainWindow extends javax.swing.JFrame {
    
    private PatternRecognizer pr;
    /**
     * Cria a janela principal.
     */
    public MainWindow() {
        super("Pattern Recognizer");
        initComponents();
        //Configurações adicionais:
        super.getContentPane().setBackground(Color.black);
        super.setLocationRelativeTo(null);
        super.setIconImage(new ImageIcon(getUrl("images/icon.png")).getImage());
        //Instância do Interpretador:
        pr = new PatternRecognizer(Pattern.CPF);
    }
    
    /**
     * Exibi uma imagem de erro.
     */
    private void showError()
    {
        ImageIcon img = new ImageIcon(getUrl("images/error.png"));
        imageLabel.setIcon(img);
    }
    
    /**
     * Exibe uma imagem de acerto.
     */
    private void showHit()
    {
        ImageIcon img = new ImageIcon(getUrl("images/accept.png"));
        imageLabel.setIcon(img);
    }
    
    /**
     * Volta a imagem inicial.
     */
    private void clearMessage()
    {
        ImageIcon img = new ImageIcon(getUrl("images/null.png"));
        imageLabel.setIcon(img);
        textField.setText("");
    }
    
    /**
     * Obtém uma URL do recurso especificado da
     * aplicação.
     * 
     * @param dir O diretório do recurso.
     * @return A URL do recurso.
     */
    private URL getUrl(String dir)
    {
        return getClass().getResource(dir);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        patternOption = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pane.setBackground(new java.awt.Color(0, 0, 0));
        pane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pane.setPreferredSize(new java.awt.Dimension(240, 165));
        pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneMouseClicked(evt);
            }
        });

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pr/gui/images/null.png"))); // NOI18N

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });

        button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pr/gui/images/button.png"))); // NOI18N
        button.setBorder(null);
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.setFocusPainted(false);
        button.setPreferredSize(new java.awt.Dimension(33, 20));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        patternOption.setBackground(new java.awt.Color(51, 255, 51));
        patternOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPF", "URL", "Email", "Phone" }));
        patternOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patternOption.setFocusable(false);
        patternOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patternOptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(patternOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patternOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        if(pr.analyze(textField.getText()))
            showHit();
        else
            showError();
    }//GEN-LAST:event_textFieldActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        if(pr.analyze(textField.getText()))
            showHit();
        else
            showError();
    }//GEN-LAST:event_buttonActionPerformed

    private void patternOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patternOptionActionPerformed
        
        switch(patternOption.getItemAt(patternOption.getSelectedIndex()))
        {
            case "CPF":
                pr = new PatternRecognizer(Pattern.CPF);
                break;
                
            case "Email":
                pr = new PatternRecognizer(Pattern.EMAIL);
                break;
                
            case "URL":
                pr = new PatternRecognizer(Pattern.URL);
                break;
                
            case "Phone":
                pr = new PatternRecognizer(Pattern.PHONE);
        }
        
        clearMessage();
    }//GEN-LAST:event_patternOptionActionPerformed

    private void paneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneMouseClicked
        clearMessage();
    }//GEN-LAST:event_paneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel pane;
    private javax.swing.JComboBox<String> patternOption;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
